
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:
  
  tflint:
  
    name: Lint Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
          
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
          
      - name: Check Terraform formatting
        run: |
          terraform fmt -check -recursive

  ansible-lint:
  
    name: Lint Ansible
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible
        
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6
